# on:
#   workflow_dispatch:
#   push:
#     branches: [main]

# name: Publish regmonkey-mathcamp-in-julia Site

# jobs:
#   build-deploy:
#     runs-on: ubuntu-latest

#     permissions:
#       contents: write

#     env:
#       JULIA_NUM_THREADS: auto   # ðŸ”¥ Julia renderé«˜é€ŸåŒ–

#     steps:
#       - name: Check out repository
#         uses: actions/checkout@v4

#       - name: Set up Quarto
#         uses: quarto-dev/quarto-actions/setup@v2

#       # Julia
#       - uses: julia-actions/setup-julia@v2

#       # set up Julia environment
#       - name: Instantiate Julia environment
#         run: julia --project=@. --startup-file=no -e 'using Pkg; Pkg.instantiate(); Pkg.precompile()'

#       - name: Render and Publish
#         uses: quarto-dev/quarto-actions/publish@v2
#         with:
#           target: gh-pages
